### ISSUE TITLE
Cannot open demo in `<iframe>`

### ISSUE THREAD

**Issue by levchak0910** [stylelint/stylelint.io#394] opened 2024-02-25 01:23 UTC
### What steps are needed to reproduce the bug?

link with code:
 https://stylelint.io/demo/#N4Igxg9gJgpiBcIA8AXGBbADgGwIZoD4AdAOyJQGcJ0ZSkB6NLPQ0uilAT2xmJNwAEwNigDmAJwCWUALRMc+GDNziYuCvBHkA5INzatKbQCMBp49oDcIyNnHwBACwp4AFACYADABoBARk8AUl8AZiDfAFZAgEprEgBfNn4hERkZADEICAc-VXQ4xLIihg5uXhBvEAAzSR4AOVwaBBAYAA9GnBgAOgA3AFc4SsgSGtFm4RIBASIW1rQSKAoZhwBtUimpmdKebEkSFBlh0ZkOXAWVKBnvdY2trh29g6PJURlVSHQaBZhZftoQG4AXVI8Qq4AgIxemXE6HwzQAVlQSGDYJgKOMbncyrt9stpiAWDAOFdMSBtjAcU8IcdTudxJcEPjCcSKqTMBAOGAKBQZI4UOhsHiZsyUCTJvjyZTDtSXm8YB8vrBfgMhQTFCyQSB4kA

open as `<iframe src="[link above]">`

### What did you expect to happen?

I wanted to work with playground via iframe

### What actually happened?

I am not sure if my actions caused the site to break, but I want to report what happened.

I tried to open stylelint.io/demo with code (via `/#hash`) in an iframe, but for some reason, it started to reload infinitely until the site went down. I suppose I made a small unconscious DoS attack (my laptop was working pretty hard)

Date and time: 25 Feb 2024 around 02:10 CET

**Comment by ybiquitous** [comment] 2024-02-26 06:24
@levchak0910 Thanks for the report. But I am afraid that I cannot reproduce the error. The demo seems to work correctly:

<img width="1033" alt="Screenshot 2024-02-26 at 15 23 56" src="https://github.com/stylelint/stylelint.io/assets/473530/d5cea95e-b740-44ac-a5ed-15bf9c291829">

I am using Firefox 123.0 on macOS Sonoma 14.3.1.

**Comment by levchak0910** [comment] 2024-02-26 09:57
@ybiquitous have you tried to open it in an iframe?

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>HTLLO</title>
</head>
<body>
<iframe src="https://stylelint.io/demo/#N4Igxg9gJgpiBcIA8AXGBbADgGwIZoD4AdAOyJQGcJ0ZSkB6NLPQ0uilAT2xmJNwAEwNigDmAJwCWUALRMc+GDNziYuCvBHkA5INzatKbQCMBp49oDcIyNnHwBACwp4AFACYADABoBARk8AUl8AZiDfAFZAgEprEgBfNn4hERkZADEICAc-VXQ4xLIihg5uXhBvEAAzSR4AOVwaBBAYAA9GnBgAOgA3AFc4SsgSGtFm4RIBASIW1rQSKAoZhwBtUimpmdKebEkSFBlh0ZkOXAWVKBnvdY2trh29g6PJURlVSHQaBZhZftoQG4AXVI8Qq4AgIxemXE6HwzQAVlQSGDYJgKOMbncyrt9stpiAWDAOFdMSBtjAcU8IcdTudxJcEPjCcSKqTMBAOGAKBQZI4UOhsHiZsyUCTJvjyZTDtSXm8YB8vrBfgMhQTFCyQSB4kA" frameborder="0"></iframe>
</body>
</html>
```

**Comment by ybiquitous** [comment] 2024-02-26 11:02
Ah, I see. I am not sure about details, but opening the demo site in `<iframe>` may need some hacks like:

https://github.com/stylelint/stylelint.io/blob/3478636e29a77be50a86f954c311ec139a1ab6af/src/pages/demo.js#L23

**Comment by ybiquitous** [comment] 2024-02-26 11:03
Honestly, I don't think we need to support this way, right?

**Comment by levchak0910** [comment] 2024-02-26 15:48
I would like to share my case.

I wanted to show the stylelint capabilities in the iframe, in a presentation I am preparing for the conference.
Initially, I was looking for other solutions like [in-browser editor](https://github.com/ota-meshi/stylelint4b/tree/master/packages/vue-stylelint-editor), but it doesn't support the content of .vue files with scss syntax. Because postcss-scss uses some nodejs api, which fails in the browser. Also, it doesn't support Vue3.

So, I decided to check how your demo is implemented. It looks quite complicated to repeat in my presentation, so I decided to show via an iframe, but infinite reload doesn't let me do it.

If you don't want to support it - it is fine, you can close the issue. I still can exit a presentation and navigate by a link.

**Comment by ybiquitous** [comment] 2024-02-27 00:16
I understand your background. Our demo is implemented by [WebContainers](https://developer.stackblitz.com/platform/webcontainers/browser-support) of StackBlitz (see also <https://github.com/stylelint/stylelint-demo/issues/351>), so please take a look at the doc.

@ota-meshi Do you have any thoughts about this issue? If nothing in particular, I will close this issue.

**Comment by ota-meshi** [comment] 2024-02-27 01:33
Cross-origin isolation is required for the demo to work.
https://developer.stackblitz.com/platform/webcontainers/browser-support#cross-origin-isolation

Stylelint site does several things to make it work.
https://github.com/stylelint/stylelint.io/blob/3478636e29a77be50a86f954c311ec139a1ab6af/netlify.toml#L6-L9
https://github.com/stylelint/stylelint.io/blob/3478636e29a77be50a86f954c311ec139a1ab6af/src/pages/demo.js#L13

**Comment by ybiquitous** [comment] 2024-02-27 01:57
@ota-meshi Thanks for sharing the info about cross-origin stuff.

@levchak0910 Please try the advice in your app. I hope you're doing well in your presentation.

**Closed by ybiquitous** 2024-02-27 01:57 UTC
Labels: status: needs clarification

**Comment by levchak0910** [comment] 2024-02-27 11:04
@ybiquitous @ota-meshi thank you both for info and support )
