### ISSUE TITLE
Why does stylelint.io crash immediately when I open it in Chrome?

### ISSUE THREAD

**Issue by wangrongding** [stylelint/stylelint.io#274] opened 2022-07-30 06:02 UTC
### Describe the documentation issue

Why does stylelint.io crash immediately when I open it in Chrome? 

This does not happen when I open any website, only stylelint.io has this problem
I don't know if anyone is like me.

![image](https://user-images.githubusercontent.com/42437658/181877027-fca9d60e-7eb2-4ec8-900b-f99965a08463.png)

### What solution would you like to see?

Can open documents normally

**Comment by ybiquitous** [comment] 2022-07-30 11:24
@wangrongding I've transferred the issue because this may be a problem with the website, not the Stylelint code.

Also, I cannot watch the video you reported... 😢 

<img width="366" alt="image" src="https://user-images.githubusercontent.com/473530/181908653-0a823541-e630-41fd-a06d-deb745859b26.png">

**Comment by wangrongding** [comment] 2022-07-30 12:25
Okay, thanks～😅
These two pictures can probably explain the problem

<img width="500" alt="image" src="https://user-images.githubusercontent.com/42437658/181913987-af8175ab-a382-4a68-9e3e-e35fc524c30e.png">

When my window doesn't shrink, the site goes down the moment it opens.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/42437658/181914083-1d973d32-845c-49e8-b1c4-f6ecb407ec16.png">

**Comment by jeddy3** [comment] 2022-07-31 15:11
@wangrongding Can you try opening the site in a Chrome incognito window with extensions turned off, please? These crashes are sometimes caused by misbehaving extensions, e.g. you've quite a few installed and the Grammarly one is erroring in your console.

**Comment by wangrongding** [comment] 2022-07-31 15:21
Indeed, it is caused by this extension
https://chrome.google.com/webstore/detail/crxmouse-chrome-gestures/jlgkpaicikihijadgifklkbpdajbkhjo
![image](https://user-images.githubusercontent.com/42437658/182033209-553415ac-9114-406c-a5b4-6b2a227f2e7d.png)

**Closed** 2022-07-31 15:21 UTC
